### ISSUE TITLE
Option to create nice DNS record for ALB, created by this plugin

### ISSUE THREAD

**Issue by denis-ryzhkov** [Hybridless/serverless-ecs-plugin#3]
Option to create nice DNS record for ALB, created by this plugin

This plugin creates ALB with unpredictable DNS name and no simple way to add a nice DNS record for it.

Please add an option like `dnsRecord` with `domainName` and `hostedZoneId` inside, and use it in this plugin code instead of the workaround below:

```yaml
resources:
  Resources:

    AlbDnsRecord:
      Type: AWS::Route53::RecordSetGroup
      DependsOn:
      - ${self:custom.albResourceName}
      Properties:
        HostedZoneId: TODO_options_dnsRecord_hostedZoneId
        RecordSets:
        - Name: TODO_options_dnsRecord_domainName
          Type: A
          AliasTarget:
            DNSName:
              Fn::GetAtt:
              - ${self:custom.albResourceName}
              - DNSName
            HostedZoneId:
              Fn::GetAtt:
              - ${self:custom.albResourceName}
              - CanonicalHostedZoneID

custom:
    albResourceName: REDACTED_ServerlessService_Stage_ALB_Env
    # ALB created by serverless-ecs-plugin
```
