### ISSUE TITLE
Sample YAML file

### ISSUE THREAD

**Issue by rhamnett** [Hybridless/serverless-ecs-plugin#5]
Hi thanks for the plugin. Can you kindly provide a sample YAML file in the readme? 

Many thanks,

**Comment by gwdp** [comment]
Hello @rhamnett, 

Below is a simple sample I commonly use:

```
service: MyService
plugins:
  - '@hybridless/serverless-ecs-plugin'
provider:
  name: aws
  stage: ${env:stage, 'local'}
  region: ${env:region, 'ca-central-1'}
ecs:
  - timeout: 10
    clusterName: Ghost
    tags:
      Test: 123
    vpc: 
      cidr: 10.0.0.0/16
      subnets: 
        - 10.0.0.0/24
        - 10.0.1.0/24
    services:
      - name: ghost
        cpu: 1024
        memory: 2048
        desiredCount: 1
        environment:
          NODE_ENV: development
        path: "/"
        image: ghost
        listeners:
          - albProtocol: HTTP
            port: 80
            containerPort: 2368
```

Let me know if you encounter any issues with it or with the configuration you might need for your service.

ps.: Adding it to readme as well.
